name: "assets-tracker"
port: 8000

logger:
  debug: true
  output: "text"

postgres:
  host: "localhost"
  user: "postgres"
  password: "password"
  dbname: "postgres"
  port: 5432
  sslmode: "disable"

redis:
  host: localhost
  port: 6379
  password:
  db: 0

jwt:
  access_token_secret: "access_token_secret"
  refresh_token_secret: "refresh_token_secret"
  access_token_expire: 604800 # 1 day
  refresh_token_expire: 2592000 # 30 days
  auto_logout: 2592000 # 30 days 2592000
